#!/usr/bin/env bash
# Configures UFW to block all incoming traffic except ports 22, 443, and 80

sudo apt-get update -y
sudo apt-get install -y ufw
sudo ufw reset
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable

