#!/usr/bin/env bash
# Configures Nginx with a custom HTTP response header X-Served-By set to the server hostname

apt-get update -y
apt-get install -y nginx

HOSTNAME=$(hostname)
CONFIG_FILE="/etc/nginx/sites-available/default"

if ! grep -q "X-Served-By" "$CONFIG_FILE"; then
    sed -i "/server_name _;/a\    add_header X-Served-By $HOSTNAME;" "$CONFIG_FILE"
fi

service nginx restart

