#!/usr/bin/env bash
# Installs and configures HAproxy on lb-01 to balance traffic between web-01 and web-02

apt-get -y update
apt-get -y install haproxy

echo "
frontend lb-frontend
        bind *:80
        mode http
        default_backend lb-backend
backend lb-backend
        balance roundrobin
        server 7030-web-01 3.82.193.211:80 check
        server 7030-web-02 44.212.20.80:80 check
" | tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | tee -a /etc/default/haproxy
service haproxy restart

